### PR TITLE
Add bundle_id parameter to apple_resource_bundle

### LINKED ISSUE #639: When bulding a resources bundle, should add plist if there are images.
Adding images to a resources framework doesn't work as expected. In theory I expect to be able to do this. 
```
apple_resource_bundle(
    name = "Resources",
    bundle_name = "MyResources",
    resources = glob([
        "Assets/**",
        "Images.xcassets/**"
    ]) 
)
```

Then I should be able to add it to my app and do something like. 
```
let bundle: Bundle = .init(url: Bundle.main.url(forResource: "MyResources, withExtension: "bundle"))
let image = Image(named: "MyImage", in: bundle, compatibleWith: nil)
```
This fails. 

I have to do the following. 

```
apple_resource_group(
    name = "Images",
    resources = glob(["Images.xcassets/**"]),
)

apple_resource_bundle(
    name = "Resources",
    bundle_name = "MyResources",
    infoplists = ["Resources.plist"],
    resources = glob([
        "Assets/**",
    ]) + [":Images"],
)
```

1. I have to make a resources group first. Even though I didn't put these in structured resources.  This will end up created the Assets.car file where images load. 
2. I have to add a plist or no images will load from this bundle.

### PR DESCRIPTION
**Pull request by steeve**
This enables having resource bundles with assets in them, since a `bundle_id` is
required for those.

Fix #639

### CODE REVIEW

**Comment by steeve** [comment]
I am unable to update the documentation:
```
$  bazel run //doc:update
INFO: Analyzed target //doc:update (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/steeve/code/github.com/znly/rules_apple/doc/BUILD.bazel:28:12: Generating proto for Starlark doc for resources_doc failed (Exit 1) stardoc failed: error executing command bazel-out/host/bin/external/io_bazel_stardoc/stardoc/stardoc '--input=//apple:resources.bzl' '--workspace_name=build_bazel_rules_apple' '--dep_roots=.' '--dep_roots=external/build_bazel_rules_apple' ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
com.google.devtools.build.skydoc.SkydocMain$StarlarkEvaluationException: File external/rules_cc/cc/defs.bzl imported '//cc/private/rules_impl:cc_flags_supplier.bzl', yet external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl was not found, even at roots [., external/build_bazel_rules_apple].
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:412)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:402)
	at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:260)
	at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:163)
Caused by: java.nio.file.NoSuchFileException: external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl
	at com.google.devtools.build.skydoc.SkydocMain.getInputSource(SkydocMain.java:454)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:385)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:402)
	... 3 more
Stardoc documentation generation failed: File external/rules_cc/cc/defs.bzl imported '//cc/private/rules_impl:cc_flags_supplier.bzl', yet external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl was not found, even at roots [., external/build_bazel_rules_apple].
Target //doc:update failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.628s, Critical Path: 0.50s
INFO: 1 process: 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

The workaround in https://github.com/bazelbuild/stardoc/issues/92 doesn't work, it fails right after with:
```
$ bazel run //doc:update
Starting local Bazel server and connecting to it...
INFO: Analyzed target //doc:update (39 packages loaded, 572 targets configured).
INFO: Found 1 target...
ERROR: /Users/steeve/code/github.com/znly/rules_apple/doc/BUILD.bazel:28:12: Generating proto for Starlark doc for tvos.doc_doc failed (Exit 1) stardoc failed: error executing command bazel-out/host/bin/external/io_bazel_stardoc/stardoc/stardoc '--input=//apple:tvos.doc.bzl' '--workspace_name=build_bazel_rules_apple' '--dep_roots=.' '--dep_roots=external/build_bazel_rules_apple' ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
com.google.devtools.build.skydoc.SkydocMain$StarlarkEvaluationException: File apple/internal/tvos_rules.bzl imported '@build_bazel_rules_apple//apple/internal/aspects:swift_dynamic_framework_aspect.bzl', yet apple/internal/aspects/swift_dynamic_framework_aspect.bzl was not found, even at roots [., external/build_bazel_rules_apple].
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:412)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:402)
	at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:260)
	at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:163)
Caused by: java.nio.file.NoSuchFileException: apple/internal/aspects/swift_dynamic_framework_aspect.bzl
	at com.google.devtools.build.skydoc.SkydocMain.getInputSource(SkydocMain.java:454)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:385)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:402)
	... 3 more
Stardoc documentation generation failed: File apple/internal/tvos_rules.bzl imported '@build_bazel_rules_apple//apple/internal/aspects:swift_dynamic_framework_aspect.bzl', yet apple/internal/aspects/swift_dynamic_framework_aspect.bzl was not found, even at roots [., external/build_bazel_rules_apple].
Target //doc:update failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.869s, Critical Path: 0.66s
INFO: 1 process: 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by thii** [comment]
```
bazel test //doc:all
bazel run //doc:update
```

**Review by thii — APPROVED** [review]
Can you add a simple test? (There's `infoplist_contents_test`)

**Comment by thii** [comment]
Nevermind, you have the tests now :)

**Review by brentleyjones — APPROVED** [review]

**Pull request merged**
