### PR TITLE
Update macOS test bundle injection path

### PR DESCRIPTION
**Pull request by keith**
The path to this binary changed with Xcode 10

Related https://github.com/facebook/xctool/pull/755/

### CODE REVIEW

**Comment by sergiocampama** [comment]
sorry it took so long to push out, but this should be fixed in the PR that thomasvl mentioned. That PR branch is already passing, so it'll be merged later today

**Comment by sergiocampama** [comment]
can you check that your tests pass by using the version at HEAD?

**Comment by keith** [comment]
Looks like I'm seeing some new errors, likely unrelated:

```
ERROR: .../BUILD:51:1: in deps attribute of swift_runtime_linkopts rule //....swift_runtime_linkopts: rule '//...' does not exist. Since this rule was created by the macro 'macos_unit_test', the error might have been caused by the macro implementation in .../external/build_bazel_rules_apple/apple/bundling/binary_support.bzl:203:16
```

**Comment by keith** [comment]
Ah it looks like this was a red herring of misconfiguration of a commented out target

**Comment by keith** [comment]
Now my tests just run forever, I'll try and debug more

**Comment by sergiocampama** [comment]
so it appears that Xcode 10 is trying to write data into DerivedData, which is outside of the sandbox that bazel creates. I can run the example `macos_unit_tests` but only if I pass the `--spawn_strategy=local` flag

**Comment by keith** [comment]
Somehow with my change this was working locally for me.


--
Keith Smiley

**Comment by sergiocampama** [comment]
Can you confirm if you can run the example tests? Or provide a small repro case where the tests hang?

**Comment by keith** [comment]
Hmm yea it looks like `bazel test //test:macos_application_resources_test` fails for me either way

**Comment by keith** [comment]
Actually sorry it looks like I didn't give this enough time. It looks like this test passes for me on master even without `--spawn_strategy=local`

**Comment by keith** [comment]
There must be a problem with our test suite, I'll try and debug more

**Comment by keith** [comment]
I am seeing this log, although it might not matter:

```
2018-10-04 23:42:26.855 xctest[16601:6628902] Bundle injected into '/Applications/Xcode-10.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Agents/xctest' but XCInjectBundleInto environment variable set to ''
```

**Comment by keith** [comment]
Ok it looks like I spoke too soon about there being an issue, it just so happens that the specific tests I'm working with crash when they fail, and that seems to add a huge amount of time to the overall runtime, so I was never patient enough to see it through. They run correctly even with the sandbox enabled.

Thanks for the fix!

**Pull request closed without merging**
