### PR TITLE
fix dynamic framework loss in implementation_deps

### PR DESCRIPTION
**Pull request by xiemotongye**
Fix https://github.com/bazelbuild/rules_apple/issues/2406

### CODE REVIEW

**Comment by brentleyjones** [comment]
Can you add a test for this? Should be able to write an archive_contents test.

**Comment by keith** [comment]
Looks great. Can you add a test covering this?

**Comment by xiemotongye** [comment]
> Can you add a test for this? Should be able to write an archive_contents test.

OK.

I've added archive_contents_test for xcframework with private_deps(swift_library) & implementation_deps(objc_library).

**Review by brentleyjones — APPROVED** [review]

**Review by keith — APPROVED** [review]
awesome, thanks!

**Comment by keith** [comment]
oop looks like the CI failures are valid

**Comment by xiemotongye** [comment]
> oop looks like the CI failures are valid

I've fix the format check failure.

It seems all test can be passed in bazel 7.x.

But I have no idea why it failed in last-green-bazel. I built the lastest bazel locally(commit: f76a27ce42537f8c76a0ea5646326a00f092b951). And run `/path/to/bazel/bazel-bin/src/bazel test //test:ios_test_runner_ui_test`. The test can be passed locally.

The CI failures seem to be unrelated to the changes:

```
ERROR: /private/var/tmp/_bazel_buildkite/5cf5fc3833ed92b42b3b811e115e98cc/sandbox/darwin-sandbox/8388/execroot/_main/_tmp/095e406d7a731ad16c0d7db1b90cfd56/workspace/ios/BUILD:54:12: TreeArtifact ios/PassingUiSwiftTest/test.outputs was not created
ERROR: /private/var/tmp/_bazel_buildkite/5cf5fc3833ed92b42b3b811e115e98cc/sandbox/darwin-sandbox/8388/execroot/_main/_tmp/095e406d7a731ad16c0d7db1b90cfd56/workspace/ios/BUILD:54:12: Testing //ios:PassingUiSwiftTest failed: not all outputs were created or valid
```

There are also some failures in bazel 6.x. Two of the new tests I added failed in bazel 6.x. These failures can be confirmed locally. But there are thousands of commits between bazel 6.5 and bazel 7. I found several changes about linkopt, ObjcProvider. But I'm not sure which commit is the key. Do you have any idea about this?

**Comment by xiemotongye** [comment]
It seems the tests can be passed in last-green-bazel.

I'm looking for why the tests failed in bazel 6.x. I think it may be a little difficult. It will be very pleasure if you have any ideas about this.

**Comment by keith** [comment]
i wonder if there was an issue with the implementation_deps implementation in 6.x, since it was added mid-way through the cycle

**Comment by xiemotongye** [comment]
Already fixed by this pull request:
https://github.com/bazelbuild/rules_apple/pull/2508

So this issue could be closed.

**Pull request closed without merging**
