### PR TITLE
Remove ios_sim support for Xcode 6

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by kastiglione** [comment]
This is a good point to ask: What's versions of Xcode should rules_apple support? Both here and in xctestrunner, there's support for older versions, however there's no indication which versions of Xcode need to be supported, and another problem is there is code in those scripts that are clearly work arounds, but not clear which version(s) of Xcode would require them.

**Comment by rahul-malik** [comment]
It seems like HEAD should support the latest major version since that’s typically required for App Store submission

**Comment by sergiocampama** [comment]
Re: which versions of Xcode we support, we don't have a policy, but as @rahul-malik mentions, we try to be up to date to the latest versions of Xcode. But as you've seen, we haven't had the time to clean the repo of old Xcode workarounds

**Comment by sergiocampama** [comment]
this change has been imported and will be exported soon

**Pull request closed without merging**
