### PR TITLE
Fix incompatible_restrict_named_params issue

### PR DESCRIPTION
**Pull request by keith**
https://github.com/bazelbuild/bazel/issues/8147

### CODE REVIEW

**Comment by c-parsons** [comment]
`incompatible_restrict_named_params` only affects builtins, of which `embedded_bundles_partial` is not. I'm confused as to what this PR has to do with `incompatible_restrict_named_params`.

**Comment by keith** [comment]
Here's what I'm seeing:

```
bazel build --config=QA --config=ci --apple_platform_type=ios //Modules/... --incompatible_restrict_named_params
INFO: Invocation ID: 1a11e921-4911-4f86-a455-10af65f2a9ee
Loading:
Loading: 0 packages loaded
Analyzing: 2224 targets (485 packages loaded, 0 targets configured)
ERROR: /Users/iosci/Desktop/src/iosci41/lyft/ios/Modules/ResourceSupport/BUILD:8:1: in ios_unit_test rule //Modules/ResourceSupport:ResourceSupportTests:
Traceback (most recent call last):
File "/Users/iosci/Desktop/src/iosci41/lyft/ios/Modules/ResourceSupport/BUILD", line 8
ios_unit_test(name = 'ResourceSupportTests')
File "/private/var/tmp/_bazel_iosci/344968675a7422486244096dde4e0573/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 44, in _ios_unit_test_impl
apple_test_rule_support.apple_test_impl(ctx, "xctest", extra_providers = [Io...()])
File "/private/var/tmp/_bazel_iosci/344968675a7422486244096dde4e0573/external/build_bazel_rules_apple/apple/internal/testing/apple_test_rule_support.bzl", line 431, in apple_test_rule_support.apple_test_impl
apple_test_bundle_support.apple_test_bundle_impl(ctx)
File "/private/var/tmp/_bazel_iosci/344968675a7422486244096dde4e0573/external/build_bazel_rules_apple/apple/internal/testing/apple_test_bundle_support.bzl", line 98, in apple_test_bundle_support.apple_test_bundle_impl
partials.embedded_bundles_partial(bundle_embedded_bundles = True, em... []))
File "/private/var/tmp/_bazel_iosci/344968675a7422486244096dde4e0573/external/build_bazel_rules_apple/apple/internal/testing/apple_test_bundle_support.bzl", line 100, in partials.embedded_bundles_partial
getattr(ctx.attr, "frameworks", default = [])
unexpected keyword 'default', for call to function getattr(x, name, default = unbound)
```

**Comment by c-parsons** [comment]
Aha. I really read your PR wrong. My bad.

(I read `default` as a parameter of `embedded_bundles_partial`, when really there was a getattr call which was the offender. **I need more coffee.**)

Indeed, we've made `default` a positional-only parameter of the builtin `getattr`. This PR looks good.

**Comment by thomasvl** [comment]
Closing since the change was merged, not sure what github sees it as merged but left this as open.

**Pull request merged**
