### PR TITLE
Have the root Info.plist tests for XCFrameworks comprehensively validate available library attributes.

### PR DESCRIPTION
**Pull request by brentleyjones**
PiperOrigin-RevId: 397874353
(cherry picked from commit 97e6829f9ece61ff232b256b6ee61b2b30c0dbac)

### CODE REVIEW

**Review by thii — APPROVED** [review]

**Comment by brentleyjones** [comment]
This might require #1271 or another xcframework PR to land first.

**Comment by thii** [comment]
Seems like GitHub can't rebranch if the base branch was deleted too fast.

**Comment by keith** [comment]
Is this one good though?

**Comment by brentleyjones** [comment]
I re-opened it in another PR, and updated the commit link.

**Pull request closed without merging**
