### PR TITLE
Updates apple_support to 1.17.0

### PR DESCRIPTION
**Pull request by jiawen**

### CODE REVIEW

**Comment by mattrobmattrob** [comment]
Hi, @jiawen. Is there a particular reason you're doing this update?

**Comment by jiawen** [comment]
> Hi, @jiawen. Is there a particular reason you're doing this update?

Mostly to get access to the new features enabled by [apple_suport 1.16.0](https://github.com/bazelbuild/apple_support/releases/tag/1.16.0).

My day job relies heavily on rules_apple. I thought I might make my first contribution with something simple.

**Comment by jiawen** [comment]
... but it looks like this actually breaks something. I can look into it.

**Comment by luispadron** [comment]
> > Hi, @jiawen. Is there a particular reason you're doing this update?
> 
> Mostly to get access to the new features enabled by [apple_suport 1.16.0](https://github.com/bazelbuild/apple_support/releases/tag/1.16.0).
> 
> My day job relies heavily on rules_apple. I thought I might make my first contribution with something simple.

Are you planning on using specific things from 1.16 in rules_apple? If not, you should instead just override the apple_support version your personal `WORKSPACE`/`MODULE`

**Comment by jiawen** [comment]
> > > Hi, @jiawen. Is there a particular reason you're doing this update?
> 
> > 
> 
> > Mostly to get access to the new features enabled by [apple_suport 1.16.0](https://github.com/bazelbuild/apple_support/releases/tag/1.16.0).
> 
> > 
> 
> > My day job relies heavily on rules_apple. I thought I might make my first contribution with something simple.
> 
> 
> 
> Are you planning on using specific things from 1.16 in rules_apple? If not, you should instead just override the apple_support version in your personal `WORKSPACE`/`MODULE`
> 
> 
> 
> Typically rule sets try to maintain a minimal version thats supported unless the API from the dependency is needed, this is to not force all users of `rules_apple` for example to have to use a newer `apple_support`

Makes sense. Yeah I'll do that and stop interrupting any plans you may already have.

**Pull request closed without merging**
