### PR TITLE
Fix :for_bazel_tests visible from Tulsi aspects

### PR DESCRIPTION
**Pull request by thii**
Fixes https://github.com/bazelbuild/tulsi/issues/120

### CODE REVIEW

**Comment by thii** [comment]
This needs to be tested using the latest Bazel from HEAD but CI is using a very old version of Bazel (pre 1.2.0)

```
2019/12/28 08:29:07 Using unreleased version at commit 11deef7582dfeec7a04ee3f7236393d9b8027367
```

**Comment by thomasvl** [comment]
Is this for some integration test?  It sounds like they should just pulled in rule_apple into the testing workspace rather than trying to pull it in via the filegroup?  Long term, we'd love to get off integration tests here and thus remove these filegroups.

**Comment by allevato** [comment]
> Long term, we'd love to get off integration tests here and thus remove these filegroups.

Yeah, increasing reliance on these is a bad idea because they're going to be going away as soon as we can realistically make it happen. @DavidGoldman's recommendation in the Tulsi issue is a better fix, IMO.

But I'm glad this pointed out that apparently our last-green configuration has been incorrect since November, but has gone undetected until now because we didn't check in any features that used newer stuff until recently.

**Comment by thii** [comment]
Submitted https://github.com/bazelbuild/tulsi/pull/121 instead.

**Pull request closed without merging**
