### PR TITLE
Disable sharding for the rules_apple shell tests by default.

### PR DESCRIPTION
**Pull request by BalestraPatrick**
PiperOrigin-RevId: 462682181
(cherry picked from commit bed5ff71f5d79a93a22d6afbb4a72ecc27800ec7)

### CODE REVIEW

**Review by keith — COMMENTED** [review]
i assume this is because the number of these tests is massively decreasing with all the other commits? if so do we have those already ?

**Comment by BalestraPatrick** [comment]
@keith Correct. A bunch of different commits are moving the tests to Starlark:
- e0b1daba0fdec92c228d91872e7ae0e3ad15b390
- c1c180c482fa58f960c8d65b071d358d53b5ce9c
- 09c134475ebf7106a61e0c8db44247dd8fde1edb
- fb84461d06152ea0d2b98a69d61ee40fe0faeb39
- cefb402016af7b3bacc3f517f18ec117efd34416

They seem pretty standalone to me. Should we cherry-pick all of them in this PR?

**Comment by keith** [comment]
separate PRs or not is up to you, but we might want to land all those first (maybe you have)

**Review by thii — APPROVED** [review]

**Comment by thii** [comment]
> i assume this is because the number of these tests is massively decreasing with all the other commits? if so do we have those already ?

In the upstream branch, this change is right after the change we're cherry-picking in https://github.com/bazelbuild/rules_apple/pull/1677. I think it's fine as long as we merge that first.

**Review by brentleyjones — APPROVED** [review]

**Comment by BalestraPatrick** [comment]
I'll be merging this first, and proceed to cherry-pick all the following commits that move the tests to Starlark in a single PR.

**Pull request merged**
