### PR TITLE
Internal change.

### PR DESCRIPTION
**Pull request by keith**
RELNOTES: None
PiperOrigin-RevId: 430984675
(cherry picked from commit 3432f12c3424e925e26177d77aefb6951cb5ce42)

### CODE REVIEW

**Comment by thii** [comment]
Might need to revert this https://github.com/bazelbuild/rules_swift/commit/bb8aea1c953d9fd2302793f230808234db1545fa - the WORKSPACE file seems required to create the sub workspace to run bazel in the test.

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_swift/pull/774

**Comment by keith** [comment]
guess this only works inside of google since they likely don't even have these files

**Comment by keith** [comment]
minor thing to not take, low chance of issues in this divergence

**Pull request closed without merging**
