### PR TITLE
Add additional_linker_inputs to linking attributes

### PR DESCRIPTION
**Pull request by segiddins**
This is to support linkopts with input files, and with $(location)
expansion.  Much of the support is done by native code that
automatically does the right thing if the additional_linker_inputs
attribute is on the rule.  This is similar to how the linkopts
attribute is supported now.

PiperOrigin-RevId: 375142378
(cherry picked from commit 48d3dcb6955c21cb77134975646281ce59fee64a)

### CODE REVIEW

**Review by keith — APPROVED** [review]
nice, makes zld integration easier

**Comment by brentleyjones** [comment]
Is there anything that we added to support zld, that this replaces, and should now be removed?

**Comment by keith** [comment]
not in rules_apple AFAIK but in individual configs probably

**Comment by brentleyjones** [comment]
Ahh, yes, we did it through a trick to get the link opts added instead :+1:.

**Comment by keith** [comment]
looks like this requires a bazel release

**Pull request merged**
