### PR TITLE
Converted two partials to the new ctx-less format. Addressed run_support to remove ctx in the process.

### PR DESCRIPTION
**Pull request by keith**
PiperOrigin-RevId: 332890021

### CODE REVIEW

**Comment by keith** [comment]
made some more changes for the custom executable_name, still lots more to do i think, not going to do it now

**Comment by thii** [comment]
I can help on that if you don't mind, since I added that attribute.

**Comment by keith** [comment]
sure, that would be great!

**Comment by keith** [comment]
you can submit a PR into this branch, or take this cherry pick and apply fixes yourself, up to you!

**Comment by thii** [comment]
https://github.com/bazelbuild/rules_apple/pull/918

**Pull request closed without merging**
