### PR TITLE
Fix app intents with Xcode 15.3+

### PR DESCRIPTION
**Pull request by keith**
Depends on https://github.com/bazelbuild/rules_swift/pull/1170

### CODE REVIEW

**Comment by pennig** [comment]
Has the time come at last?

**Comment by BalestraPatrick** [comment]
Yes, we just need a new `rules_swift` release I believe depending on when we're happy with the status of the cherry-picks there

**Comment by brentleyjones** [comment]
@BalestraPatrick can you update this to point to the **rules_swift** 2.0.0-rc1 release? I'm going to create a release without this change, which is compatible but doesn't require **rules_swift** 2.0, and then once that is out we can start depending on it in order to merge this?

**Comment by BalestraPatrick** [comment]
@brentleyjones Updated now. I also pushed a possible fix for one breaking change (`target_name` related), but there's another breaking change as expected for the symbol graph API which seems to be more involved since we need to switch to using the aspect instead (https://github.com/bazelbuild/rules_apple/issues/2445):
```
Error: 'struct' value has no field or method 'symbol_graph'
```

**Comment by keith** [comment]
@BalestraPatrick looks like this is validated on CI now https://github.com/bazelbuild/rules_apple/issues/2488

**Comment by BalestraPatrick** [comment]
I left a comment here: https://github.com/bazelbuild/rules_apple/issues/2488#issuecomment-2216991527

But it looks on rules_apple side we also need to fix the docc rules (https://github.com/bazelbuild/rules_apple/pull/2487) in order to bump to rules_swift 2.0.0 which is required for this PR to be merged.

**Review by luispadron — APPROVED** [review]

**Comment by luispadron** [comment]
The failures are due to DocC rules needing to be updated for rules_swift 2.0, thats being done over in: #2487

**Pull request merged**
