### PR TITLE
Show example of failing label issue

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by fmeum** [comment]
This strict has more labels that aren't mapped in this way, can they be the cause of this failure?

**Comment by keith** [comment]
updated

**Comment by fmeum** [comment]
The remaining failure is due to https://github.com/bazelbuild/rules_apple/blob/681ab8e588a3e19a575f57bf68493500fd45463b/test/starlark_tests/apple_dynamic_xcframework_import_tests.bzl#L191-L193, which you also need to fix in this way.

**Comment by brentleyjones** [comment]
https://github.com/bazelbuild/rules_apple/pull/2263

**Pull request closed without merging**
