### PR TITLE
Add explicit test type to test runner execution

### PR DESCRIPTION
**Pull request by ivan-golub**
Currently rules apple and rules ios unit test targets rely on xctestrunner [automatic test type detection](https://github.com/google/xctestrunner/blob/7f8fc81b10c8d93f09f6fe38b2a3f37ba25336a6/test_runner/xctest_session.py#L343) which works fine until you write unit test for library that depend on XCUIApplication, for example UITests helper lib. This results in unit tests being run as ui test, which in most cases result a failure like this:
```
ivan.golub@MV43T917V1 phantom % ./bazelw test //Libraries/SCUITests:SCUITestsTests
INFO: Invocation ID: 84b521c5-b630-4af2-aa1e-ccd32c162cf4
INFO: Analyzed target //Libraries/SCUITests:SCUITestsTests (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[1 / 2] Testing //Libraries/SCUITests:SCUITestsTests; 0s local
==================== Test output for //Libraries/SCUITests:SCUITestsTests:
2022-02-19 05:53:10,103 Creating a new simulator:
Name: New-iPhone 13-15.0
OS: iOS 15.0
Type: iPhone 13
2022-02-19 05:53:10,815 Created new simulator 03D2BAAB-826C-4CF4-B77B-ED5E55398834.
2022-02-19 05:53:10,889 Will consider the test as test type xcuitest to run.
2022-02-19 05:53:10,889 Deleting simulator 03D2BAAB-826C-4CF4-B77B-ED5E55398834 asynchronously.
Traceback (most recent call last):
  File "/Users/ivan.golub/Snapchat/Dev/.cache/_bazel_root/e7e39dff3153e0ed28e9964aecdc85fa/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/Libraries/SCUITests/SCUITestsTests.runfiles/xctestrunner/test_runner/ios_test_runner.py", line 319, in <module>
    sys.exit(main(sys.argv))
  File "/Users/ivan.golub/Snapchat/Dev/.cache/_bazel_root/e7e39dff3153e0ed28e9964aecdc85fa/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/Libraries/SCUITests/SCUITestsTests.runfiles/xctestrunner/test_runner/ios_test_runner.py", line 313, in main
    exit_code = args.func(args)
  File "/Users/ivan.golub/Snapchat/Dev/.cache/_bazel_root/e7e39dff3153e0ed28e9964aecdc85fa/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/Libraries/SCUITests/SCUITestsTests.runfiles/xctestrunner/test_runner/ios_test_runner.py", line 216, in _SimulatorTest
    return _RunSimulatorTest(args)
  File "/Users/ivan.golub/Snapchat/Dev/.cache/_bazel_root/e7e39dff3153e0ed28e9964aecdc85fa/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/Libraries/SCUITests/SCUITestsTests.runfiles/xctestrunner/test_runner/ios_test_runner.py", line 195, in _RunSimulatorTest
    session.Prepare(
  File "/Users/ivan.golub/Snapchat/Dev/.cache/_bazel_root/e7e39dff3153e0ed28e9964aecdc85fa/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/Libraries/SCUITests/SCUITestsTests.runfiles/xctestrunner/test_runner/xctest_session.py", line 132, in Prepare
    test_type = _FinalizeTestType(
  File "/Users/ivan.golub/Snapchat/Dev/.cache/_bazel_root/e7e39dff3153e0ed28e9964aecdc85fa/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/Libraries/SCUITests/SCUITestsTests.runfiles/xctestrunner/test_runner/xctest_session.py", line 370, in _FinalizeTestType
    raise ios_errors.IllegalArgumentError(
xctestrunner.shared.ios_errors.IllegalArgumentError: The app under test is required in test type xcuitest.
================================================================================
//Libraries/SCUITests:SCUITestsTests                                     FAILED in 1.5s
  /Users/ivan.golub/Snapchat/Dev/.cache/_bazel_root/e7e39dff3153e0ed28e9964aecdc85fa/execroot/__main__/bazel-out/darwin_arm64-fastbuild/testlogs/Libraries/SCUITests/SCUITestsTests/test.log

FAIL: //Libraries/SCUITests:SCUITestsTests (see /Users/ivan.golub/Snapchat/Dev/.cache/_bazel_root/e7e39dff3153e0ed28e9964aecdc85fa/execroot/__main__/bazel-out/darwin_arm64-fastbuild/testlogs/Libraries/SCUITests/SCUITestsTests/test.log)
ERROR: /Users/ivan.golub/Snapchat/Dev/phantom/Libraries/SCUITests/BUILD.bazel:3:18: Testing //Libraries/SCUITests:SCUITestsTests failed: Test failed, aborting
Target //Libraries/SCUITests:SCUITestsTests up-to-date:
  bazel-bin/Libraries/SCUITests/SCUITestsTests
  bazel-out/applebin_ios-ios_x86_64-fastbuild-ST-70a2d60cb7ad/bin/Libraries/SCUITests/SCUITestsTests.zip
ERROR: Test failed, aborting
INFO: Elapsed time: 4.422s (0.07m), Critical Path: 1.62s (0.03m)
INFO: 2 processes: 2 internal.
INFO: Build Event Protocol files produced successfully.
INFO: Build completed, 1 test FAILED, 2 total actions
```

In order to avoid this problem we should pass test_type to xctest runner explicitly using existing substitutions in template.

### CODE REVIEW

**Comment by keith** [comment]
Thanks! Can you add a test case?

**Comment by keith** [comment]
i think the failures here are related, maybe the unit test isn't setup the way you need?

**Comment by yongjincho92** [comment]
> i think the failures here are related, maybe the unit test isn't setup the way you need?
If we rename the new test method to not have `test` prefix (so that XCUIApplication would show up on nm on test bundle, but not instantiated within unit test context), it should work as expected.

**Comment by ivan-golub** [comment]
Thx @keith @yongjincho92. I add dummy function to include required symbols. Actually calling anything from XCUI failed in UnitTest enviroment

**Comment by keith** [comment]
is that ok with your original issue?

**Comment by ivan-golub** [comment]
yeah, original issue is fixed. only thing that was remaining is was to add test case. current version of test will fail on master but will pass with my change

**Comment by keith** [comment]
Thanks!

**Review by keith — APPROVED** [review]

**Pull request merged**
