### PR TITLE
Gather resources from swift’s private deps

### PR DESCRIPTION
**Pull request by naluhh**
Resources were not propagated if you depend on a module privately.

### CODE REVIEW

**Comment by keith** [comment]
Makes sense! Can you add a test?

**Comment by brentleyjones** [comment]
@naluhh Can you add a test to make sure we don't regress this fix?

**Comment by keith** [comment]
Looks good! Can you add a test validating the resources get picked up as expected?

**Comment by keith** [comment]
this change happened at some point. i don't think it's tested either

**Pull request closed without merging**
