### PR TITLE
Support running tests on device

### PR DESCRIPTION
**Pull request by thii**
Testing on device can be done by passing
`--test_arg=--destination=platform=ios_device,id=YOUR_DEVICE_UDID`
to your `bazel test` command.

### CODE REVIEW

**Review by keith — APPROVED** [review]
nice, didn't know this would "just work"

**Review by brentleyjones — APPROVED** [review]

**Comment by brentleyjones** [comment]
@thii Is this waiting for anything?

**Comment by thii** [comment]
Still having some codesigning issue, seems like this is not enough.

**Comment by jiawen** [comment]
> Still having some codesigning issue, seems like this is not enough.

I got this working. Had to code sign the `ios_unit_test` as well. More details in #1215.

**Comment by keith** [comment]
So maybe we could require a profile in the case you want to run this way? 🤔

**Comment by jiawen** [comment]
> So maybe we could require a profile in the case you want to run this way? 🤔

Makes sense to me. We should just document it - in `ios_unit_test` and `ios_ui_test` and ideally also in an example. As part of a tutorial, I'd have the test fail by default. Then as step 2, the user brings their own provisioning profile to make it pass.

It's hard to test but testing anything on device is hard :).

**Comment by jiawen** [comment]
Anything preventing this PR from being merged? I assume the test failures are unrelated?

**Comment by thii** [comment]
Thanks for verifying. Rebased and all tests passed now, so I'm merging this.

**Pull request merged**
