### PR TITLE
Update xcarchive dsyms tests

### PR DESCRIPTION
**Pull request by maxwellE**
This should check to see that the dsym binary does exist

### CODE REVIEW

**Review by luispadron — APPROVED** [review]

**Comment by tinder-maxwellelliott** [comment]
@luispadron Are you seeing these binaries being created?

**Comment by luispadron** [comment]
I believe so yes, I'll double check today. We use it with `--apple_generate_dsym` and output_groups.

**Comment by maxwellE** [comment]
> I believe so yes, I'll double check today. We use it with `--apple_generate_dsym` and output_groups.

I am certain that we are setting these in our invocation. Is there any way you can share a trimmed down invocation for me to see? 

Regardless this test should be passing right if the dSYMs are properly copied into the xcarchive?

**Comment by luispadron** [comment]
We're still validating our releases with Bazel and don't ship with it yet but our xcarchive generated by this rule looks like:

Screenshot 2024-02-07 at 5 46 09 PM

> Regardless this test should be passing right if the dSYMs are properly copied into the xcarchive?

I thought it wouldn't pass here unless you're able to set those flags when the test runs which I don't believe the tests do.

**Comment by maxwellE** [comment]
> We're still validating our releases with Bazel and don't ship with it yet but our xcarchive generated by this rule looks like:
> Screenshot 2024-02-07 at 5 46 09 PM
> 
> > Regardless this test should be passing right if the dSYMs are properly copied into the xcarchive?
> 
> I thought it wouldn't pass here unless you're able to set those flags when the test runs which I don't believe the tests do.

What if you inspect those dSYMs, do they contain valid `Contents/Resources/DWARF/TARGET_NAME` binray paths? They need those binaries to be valid dsyms

**Comment by luispadron** [comment]
Superseded by https://github.com/bazelbuild/rules_apple/pull/2396 that PR adds the test and gets it green. Thanks for raising this @maxwellE

**Pull request closed without merging**
