### PR TITLE
Update module name API call

### PR DESCRIPTION
**Pull request by keith**
This was removed from SwiftInfo https://github.com/bazelbuild/rules_swift/commit/c512f8e59b4c9084cede72276bbf30f6df4342f7

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
Looks good! Any idea how this happened? I thought we specified a fixed version of `rules_swift`: https://github.com/bazelbuild/rules_apple/blob/73f12ab72777d6863693e33bc9128552f1dd5361/apple/repositories.bzl#L123

**Review by BalestraPatrick — APPROVED** [review]

**Comment by keith** [comment]
we test against the fixed version and HEAD

**Comment by segiddins** [comment]
Whoops, I also did this in https://github.com/bazelbuild/rules_apple/pull/906/commits/856627e70ae24240c61ca96389071fdb8e1fa2f9

**Review by thii — APPROVED** [review]

**Review by brentleyjones — APPROVED** [review]

**Comment by keith** [comment]
Merging this one with the buildifier fixes and in case you decide not to on the other

**Pull request merged**
