### PR TITLE
Add stardoc for tvos

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by alexeagle** [comment]
Hmm, the delta looks strange. Compare master
https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-tvos.md#tvos_framework
with this PR
https://github.com/bazelbuild/rules_apple/blob/c44fb3f62118373772a5b1e22d467c5e459cb384/doc/rules-tvos.md#tvos_framework

the attributes for `tvos_framework` are quite different.
Seems like we didn't see this problem for `watchos` because the _framework rules aren't documented there.

Any suggestion @keith ?

**Comment by keith** [comment]
Is there one specifically you're feeling suspect about? Looking over it briefly it looks like the master ones were just very outdated

**Comment by alexeagle** [comment]
@googlebot I fixed it.

**Comment by alexeagle** [comment]
@keith sorry it took me a while to find time for this goose chase again ;)
Yeah I think very out-of-date is an explanation, if you think it's possible that many edits were made to the starlark code since the last time the docs were generated.

**Comment by thii** [comment]
Looks like your branch is outdated. The unrelated failure is already fixed on the master branch. Please rebase your branch.

**Review by keith — APPROVED** [review]

**Comment by alexeagle** [comment]
err, ready to merge now 👍🏻

**Pull request merged**
