### PR TITLE
Don't use entitlements file for signing Frameworks that are inside an app

### LINKED ISSUE #181: ios: Signing frameworks with the same entitlements as the app causes appstore submission to fail
Submitting the `.ipa` through fastlane I get:
```
[16:28:18]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '<TEAMID>.<appid>' for key 'application-identifier' in '<path to framework>' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
Return status of iTunes Transporter was 1: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '<TEAMID>.<appid>' for key 'application-identifier' in '<path to framework>' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

[!] Error uploading ipa file, for more information see above

```

I don't know if this is something Apple changed recently, but the frameworks should not be getting signed with an entitlements file. I'll have a PR fixing it shortly.

### PR DESCRIPTION
**Pull request by jfaust**
Fixes #181 

Getting the CLA process going but wanted to start the discussion now.

### CODE REVIEW

**Comment by jfaust** [comment]
CLA is signed

**Comment by thomasvl** [comment]
@jfaust was it the corp cla or an individual one?  Looks like the bot might be having issues finding it.

**Comment by jfaust** [comment]
@thomasvl Corp CLA - but I'm realizing that this github account has both email addresses associated, and that my corp one is not the primary.

What's the best way for me get the bot to work? I can add my home address to the google group associated with the CLA, or ... ?

**Comment by thomasvl** [comment]
The account that matters is the one in the patch (you can see the authors in a PR by looking at the patch which you can get by appending `.patch` to the PR URL).

The Corp ones take a little longer on the Google side (partially a manual process I believe), so we can check on it again in a few days.  Luckily once it is done, you are good for all google repos.

**Comment by jfaust** [comment]
Oh great - that should work then.

**Comment by jfaust** [comment]
@thomasvl what do I need to do to get the bot to re-check the CLA?

**Comment by thomasvl** [comment]
Sorry, we out for a bit.  The comment was all we needed, but can you update for the new conflicts?

**Comment by jfaust** [comment]
@thomasvl finally got back to this - I think this is good to go

**Comment by jfaust** [comment]
Any update on getting this merged? We're maintaining a fork but would love to switch back to the `rules_apple` releases.

**Comment by thomasvl** [comment]
@sergiocampama since he's been working on a cleanup of the packing and this likely will come into play there also.

**Comment by jfaust** [comment]
hey @sergiocampama - yes, but it may take me a little while to get to it

**Comment by sergiocampama** [comment]
np

**Comment by jfaust** [comment]
Or maybe not so long... I believe this is ready to go @sergiocampama

**Comment by jfaust** [comment]
@sergiocampama done

**Comment by sergiocampama** [comment]
I imported the PR, pushing it out now. Took a small liberty to format a line that was longer than 100 though, hope that's ok

**Comment by jfaust** [comment]
Of course.

**Pull request closed without merging**
