### PR TITLE
Expand "Make" variables inside of values in the env dictionary on test rules

### PR DESCRIPTION
**Pull request by aaronsky**
Makes "Make" variables usable inside the `env` attr on test rules.

Despite the leveraged API being deprecated for years now, this approach has proven effective in my own codebase.

### CODE REVIEW

**Comment by aaronsky** [comment]
I think I've gotten the docs and tests in order, but willing to revise if the testing is insufficient.

**Review by keith — APPROVED** [review]
Nice!

**Comment by rasberik** [comment]
This is breaking when MY_VAR is not defined. Im looking for some way to treat it as empty string as before:

${MY_VAR:-}: not allowed
$(MY_VAR:-) behaves same way as $(MY_VAR): not defined

```
env = {
     "MY_VAR": "$(MY_VAR)",
},
```

Any suggestions?

**Comment by aaronsky** [comment]
have you tried the remediation step described in the 3.6.0 release notes? https://github.com/bazelbuild/rules_apple/releases/tag/3.6.0

**Comment by rasberik** [comment]
@aaronsky Thanks,
You mean the escape with $$? Yes, but when used from Xcode:
`ProcessInfo.processInfo.environment["MY_VAR"]` // `"$(MY_VAR)"`

It might be issue with xcoderules or something in between, looking for best option to resolve it 🙏🏻

**Pull request merged**
