### PR TITLE
Multiple updates

### PR DESCRIPTION
**Pull request by sergiocampama**

### CODE REVIEW

**Comment by sergiocampama** [comment]
Dropping, need to update rules_swift dependency

**Comment by keith** [comment]
Any plans on when this will be merged?

**Comment by thomasvl** [comment]
See @sergiocampama last comment, it got dropped.  We hit a catch in that rule_swift needs updating, but that is blocked on a breaking change in bazel's releases itself.  We are working to get things resolved through a the chain of dependency to clear things for release again.

**Comment by keith** [comment]
> See @sergiocampama last comment, it got dropped

I assume this doesn't mean it's dropped forever?

> We are working to get things resolved through a the chain of dependency to clear things for release again.

Any idea how long this will take to work out? I'm just worried since these changes are so long they'll be pretty disruptive if we try to contribute before they're merged.

**Comment by allevato** [comment]
Unfortunately if it weren't for the mass-reformatting commit sandwiched in there, this PR wouldn't be as disruptive since much of it is experimental work and refactoring. 😕 

I'm going to try to get the prerequisite rules_swift changes pushed tomorrow (I've been doing some large refactors there too), but as Thomas said those changes won't be compatible with the latest Bazel release (0.15.2), so using them will require building Bazel from HEAD until the next non-cherry-pick release. That should get these changes unblocked though (at least insofar as we can get CI green against HEAD).

**Comment by thomasvl** [comment]
> Can you reformat HEAD right now without any other code changes to make this PR a bit less disruptive?

You mean just for the formatting changes?

**Comment by sergiocampama** [comment]
bazel 0.16.0 has just been released, so we're making sure that rules_swift and rules_apple are compatible and we'll push out

**Comment by rahul-malik** [comment]
Yeah for the formatting changes (assuming that is causing a lot of the diff as suggested earlier)

**Pull request closed without merging**
